// App control
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CREATE_RESOURCE_AND_REDIRECT = 'CREATE_RESOURCE_AND_REDIRECT';
export const GET_RESOURCE = 'GET_RESOURCE';
export const RESET_FLASHCARDS_STATE = 'RESET_FLASHCARDS_STATE';

// Async related
export const ASYNC_START = 'ASYNC_START';

// Authentication Related
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const UPDATE_AUTH_FIELD = 'UPDATE_AUTH_FIELD';

// Flashcard related
export const UPDATE_FLASHCARD_FIELD = 'UPDATE_FLASHCARD_FIELD';
export const CREATE_DECK = 'CREATE_DECK';
export const CREATE_DECK_PAGE_UNLOADED = 'CREATE_DECK_PAGE_UNLOADED';
export const EDIT_DECK_PAGE_UNLOADED = 'EDIT_DECK_PAGE_UNLOADED';
export const GET_DECK_EDIT_DATA = 'GET_DECK_EDIT_DATA';
export const EMPTY_EDITABLE_FIELD_FOUND = 'EMPTY_EDITABLE_FIELD_FOUND';
export const EDITABLE_FIELD_HAS_VALUE = 'EDIATBLE_FIELD_HAS_VALUE';
export const CARD_DATA_FIELD_UPDATE = 'CARD_DATA_FIELD_UPDATE';
export const BLUR_DATA_FIELD_UPDATE = 'BLUR_DATA_FIELD_UPDATE';
export const UPDATE_ROWS = 'UPDATE_ROWS';
export const UPDATE_SNACKBAR_TRIGGER = 'UPDATE_SNACKBAR_TRIGGER';
export const GET_DECKS = 'GET_DECKS';
export const GET_PLAY_DECK = 'GET_PLAY_DECK';
export const PLAY_DECK = 'PLAY_DECK';
